package com.book.pojo;

import java.util.Date;

public class TbBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.book_name
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.sell_point
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String sellPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.author
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.image
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.cid
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.status
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.id
     *
     * @return the value of tb_book.id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.id
     *
     * @param id the value for tb_book.id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.book_name
     *
     * @return the value of tb_book.book_name
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.book_name
     *
     * @param bookName the value for tb_book.book_name
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.sell_point
     *
     * @return the value of tb_book.sell_point
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.sell_point
     *
     * @param sellPoint the value for tb_book.sell_point
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.author
     *
     * @return the value of tb_book.author
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.author
     *
     * @param author the value for tb_book.author
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.price
     *
     * @return the value of tb_book.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.price
     *
     * @param price the value for tb_book.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.num
     *
     * @return the value of tb_book.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.num
     *
     * @param num the value for tb_book.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.image
     *
     * @return the value of tb_book.image
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.image
     *
     * @param image the value for tb_book.image
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.cid
     *
     * @return the value of tb_book.cid
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.cid
     *
     * @param cid the value for tb_book.cid
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.status
     *
     * @return the value of tb_book.status
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.status
     *
     * @param status the value for tb_book.status
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.created
     *
     * @return the value of tb_book.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.created
     *
     * @param created the value for tb_book.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.updated
     *
     * @return the value of tb_book.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.updated
     *
     * @param updated the value for tb_book.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}