package com.book.pojo;

import java.util.Date;

public class TbBookDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_desc.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_desc.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_desc.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_desc.book_desc
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String bookDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_desc.book_id
     *
     * @return the value of tb_book_desc.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_desc.book_id
     *
     * @param bookId the value for tb_book_desc.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_desc.created
     *
     * @return the value of tb_book_desc.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_desc.created
     *
     * @param created the value for tb_book_desc.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_desc.updated
     *
     * @return the value of tb_book_desc.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_desc.updated
     *
     * @param updated the value for tb_book_desc.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_desc.book_desc
     *
     * @return the value of tb_book_desc.book_desc
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getBookDesc() {
        return bookDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_desc.book_desc
     *
     * @param bookDesc the value for tb_book_desc.book_desc
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setBookDesc(String bookDesc) {
        this.bookDesc = bookDesc == null ? null : bookDesc.trim();
    }
}