package com.book.pojo;

import java.util.Date;

public class TbLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.id
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.nickname
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_mobile
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_phone
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_state
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_city
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_district
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_address
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.flag
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.receiver_zip
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.created
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.updated
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.id
     *
     * @return the value of tb_location.id
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.id
     *
     * @param id the value for tb_location.id
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.nickname
     *
     * @return the value of tb_location.nickname
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.nickname
     *
     * @param nickname the value for tb_location.nickname
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_mobile
     *
     * @return the value of tb_location.receiver_mobile
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_mobile
     *
     * @param receiverMobile the value for tb_location.receiver_mobile
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_phone
     *
     * @return the value of tb_location.receiver_phone
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_phone
     *
     * @param receiverPhone the value for tb_location.receiver_phone
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_state
     *
     * @return the value of tb_location.receiver_state
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_state
     *
     * @param receiverState the value for tb_location.receiver_state
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_city
     *
     * @return the value of tb_location.receiver_city
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_city
     *
     * @param receiverCity the value for tb_location.receiver_city
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_district
     *
     * @return the value of tb_location.receiver_district
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_district
     *
     * @param receiverDistrict the value for tb_location.receiver_district
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_address
     *
     * @return the value of tb_location.receiver_address
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_address
     *
     * @param receiverAddress the value for tb_location.receiver_address
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.flag
     *
     * @return the value of tb_location.flag
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.flag
     *
     * @param flag the value for tb_location.flag
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.receiver_zip
     *
     * @return the value of tb_location.receiver_zip
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.receiver_zip
     *
     * @param receiverZip the value for tb_location.receiver_zip
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.created
     *
     * @return the value of tb_location.created
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.created
     *
     * @param created the value for tb_location.created
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.updated
     *
     * @return the value of tb_location.updated
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_location.updated
     *
     * @param updated the value for tb_location.updated
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}