package com.book.pojo;

import java.util.Date;

/**
 * 三级关联表的实体类
 * @ClassName: TbOrderAll
 * @Title: TbOrderAll
 * @author: 码农界的小学生
 * @date: 2019年8月21日
 */
public class TbOrderAll extends TbOrder{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.nickname
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.book_id
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.num
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.book_name
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.price
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.total_fee
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.pic_path
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String picPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.order_id
     *
     * @return the value of tb_order_book.order_id
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.nickname
     *
     * @return the value of tb_order_book.nickname
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.nickname
     *
     * @param nickname the value for tb_order_book.nickname
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.book_id
     *
     * @return the value of tb_order_book.book_id
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.book_id
     *
     * @param bookId the value for tb_order_book.book_id
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.num
     *
     * @return the value of tb_order_book.num
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.num
     *
     * @param num the value for tb_order_book.num
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.book_name
     *
     * @return the value of tb_order_book.book_name
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.book_name
     *
     * @param bookName the value for tb_order_book.book_name
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.price
     *
     * @return the value of tb_order_book.price
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.price
     *
     * @param price the value for tb_order_book.price
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.total_fee
     *
     * @return the value of tb_order_book.total_fee
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.total_fee
     *
     * @param totalFee the value for tb_order_book.total_fee
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.pic_path
     *
     * @return the value of tb_order_book.pic_path
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.pic_path
     *
     * @param picPath the value for tb_order_book.pic_path
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_name
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_mobile
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_phone
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_state
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_city
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_district
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_address
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shipping.receiver_zip
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    private String receiverZip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_name
     *
     * @return the value of tb_order_shipping.receiver_name
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_name
     *
     * @param receiverName the value for tb_order_shipping.receiver_name
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_mobile
     *
     * @return the value of tb_order_shipping.receiver_mobile
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_mobile
     *
     * @param receiverMobile the value for tb_order_shipping.receiver_mobile
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_phone
     *
     * @return the value of tb_order_shipping.receiver_phone
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_phone
     *
     * @param receiverPhone the value for tb_order_shipping.receiver_phone
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_state
     *
     * @return the value of tb_order_shipping.receiver_state
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_state
     *
     * @param receiverState the value for tb_order_shipping.receiver_state
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_city
     *
     * @return the value of tb_order_shipping.receiver_city
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_city
     *
     * @param receiverCity the value for tb_order_shipping.receiver_city
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_district
     *
     * @return the value of tb_order_shipping.receiver_district
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_district
     *
     * @param receiverDistrict the value for tb_order_shipping.receiver_district
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_address
     *
     * @return the value of tb_order_shipping.receiver_address
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_address
     *
     * @param receiverAddress the value for tb_order_shipping.receiver_address
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shipping.receiver_zip
     *
     * @return the value of tb_order_shipping.receiver_zip
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shipping.receiver_zip
     *
     * @param receiverZip the value for tb_order_shipping.receiver_zip
     *
     * @mbggenerated Tue Aug 20 13:55:35 CST 2019
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }
}
