package com.book.pojo;

public class TbOrderBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.order_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.nickname
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.book_name
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.total_fee
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_book.pic_path
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String picPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.order_id
     *
     * @return the value of tb_order_book.order_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.order_id
     *
     * @param orderId the value for tb_order_book.order_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.nickname
     *
     * @return the value of tb_order_book.nickname
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.nickname
     *
     * @param nickname the value for tb_order_book.nickname
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.book_id
     *
     * @return the value of tb_order_book.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.book_id
     *
     * @param bookId the value for tb_order_book.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.num
     *
     * @return the value of tb_order_book.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.num
     *
     * @param num the value for tb_order_book.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.book_name
     *
     * @return the value of tb_order_book.book_name
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.book_name
     *
     * @param bookName the value for tb_order_book.book_name
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.price
     *
     * @return the value of tb_order_book.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.price
     *
     * @param price the value for tb_order_book.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.total_fee
     *
     * @return the value of tb_order_book.total_fee
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.total_fee
     *
     * @param totalFee the value for tb_order_book.total_fee
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_book.pic_path
     *
     * @return the value of tb_order_book.pic_path
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_book.pic_path
     *
     * @param picPath the value for tb_order_book.pic_path
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }
}