package com.book.pojo;

import java.util.Date;

public class TbUserCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.nicename
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String nicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.image
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_car.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.id
     *
     * @return the value of tb_user_car.id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.id
     *
     * @param id the value for tb_user_car.id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.nicename
     *
     * @return the value of tb_user_car.nicename
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getNicename() {
        return nicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.nicename
     *
     * @param nicename the value for tb_user_car.nicename
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setNicename(String nicename) {
        this.nicename = nicename == null ? null : nicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.book_id
     *
     * @return the value of tb_user_car.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.book_id
     *
     * @param bookId the value for tb_user_car.book_id
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.price
     *
     * @return the value of tb_user_car.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.price
     *
     * @param price the value for tb_user_car.price
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.num
     *
     * @return the value of tb_user_car.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.num
     *
     * @param num the value for tb_user_car.num
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.image
     *
     * @return the value of tb_user_car.image
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.image
     *
     * @param image the value for tb_user_car.image
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.created
     *
     * @return the value of tb_user_car.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.created
     *
     * @param created the value for tb_user_car.created
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_car.updated
     *
     * @return the value of tb_user_car.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_car.updated
     *
     * @param updated the value for tb_user_car.updated
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}