package com.book.mapper;

import com.book.pojo.TbBookCat;
import com.book.pojo.TbBookCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBookCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int countByExample(TbBookCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int deleteByExample(TbBookCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int insert(TbBookCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int insertSelective(TbBookCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    List<TbBookCat> selectByExample(TbBookCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    TbBookCat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbBookCat record, @Param("example") TbBookCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByExample(@Param("record") TbBookCat record, @Param("example") TbBookCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByPrimaryKeySelective(TbBookCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_cat
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByPrimaryKey(TbBookCat record);
}