package com.book.mapper;

import com.book.pojo.TbBook;
import com.book.pojo.TbBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int countByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int deleteByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int insert(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int insertSelective(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    List<TbBook> selectByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    TbBook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbBook record, @Param("example") TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByExample(@Param("record") TbBook record, @Param("example") TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByPrimaryKeySelective(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByPrimaryKey(TbBook record);
}