package com.book.mapper;

import com.book.pojo.TbLocation;
import com.book.pojo.TbLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int countByExample(TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int deleteByExample(TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int insert(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int insertSelective(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    List<TbLocation> selectByExample(TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    TbLocation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbLocation record, @Param("example") TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int updateByExample(@Param("record") TbLocation record, @Param("example") TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int updateByPrimaryKeySelective(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated Sun Aug 25 16:39:34 CST 2019
     */
    int updateByPrimaryKey(TbLocation record);
}