package com.book.mapper;

import com.book.pojo.TbOrderBook;
import com.book.pojo.TbOrderBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbOrderBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int countByExample(TbOrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int deleteByExample(TbOrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int insert(TbOrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int insertSelective(TbOrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    List<TbOrderBook> selectByExample(TbOrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    TbOrderBook selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbOrderBook record, @Param("example") TbOrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByExample(@Param("record") TbOrderBook record, @Param("example") TbOrderBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByPrimaryKeySelective(TbOrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_book
     *
     * @mbggenerated Wed Aug 21 15:37:39 CST 2019
     */
    int updateByPrimaryKey(TbOrderBook record);
}